[build]
target = "x86_64-os.json"

rustflags = [
    "-C", "link-arg=-Ttext=0x100000",
    "-C", "link-arg=-entry=_start",
    "-C", "link-arg=--image-base=0x100000",
]

[unstable]
json-target-spec = true
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]
panic-abort-tests = true